//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VehicleInventoryApplication.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class vehicleinventory
    {
        [Required(ErrorMessage ="This field is required to continue")]
        public int vehicleid { get; set; }
        [Required(ErrorMessage = "This field is required to continue")]
        public string Make { get; set; }
        [Required(ErrorMessage = "This field is required to continue")]
        public string Model { get; set; }
        [Required(ErrorMessage = "This field is required to continue")]
        public Nullable<int> Year { get; set; }
        [Required(ErrorMessage = "This field is required to continue")]
        public string VIN { get; set; }
    }
}
